### ISSUE TITLE
Support counting words

### ISSUE THREAD

**Issue by craftzdog** [bildeneins/character-count#1]
Hi, thanks for creating a great plugin!
It would be awesome to support counting words as well.

You can use the [words-count](https://github.com/byn9826/words-count) module. Or, you can use [this regex](https://forum.inkdrop.app/t/word-counter/2129/3) posted on the user forum.
It would affect performance, so you can debounce the process by using a module like [lodash.debounce](https://www.npmjs.com/package/lodash.debounce).

**Comment by bildeneins** [comment]
Hi, thank you for giving an idea to me.
Sounds like a good feature! I will work on it.

**Comment by bildeneins** [comment]
@craftzdog Just added a word count feature! I hope you will check it out.
Your advice was very helpful in the implementation. Thank you very much.

**Comment by craftzdog** [comment]
Cool! Thank you for improving the plugin :D
Works perfectly.

![demo](https://user-images.githubusercontent.com/1332805/205224963-0b27e210-5bc3-4a53-9bf4-c2168720b2a8.png)
